# Generated by Django 4.1.3 on 2022-11-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="username",
            new_name="nickname",
        ),
    ]
